### ISSUE TITLE
On back click event(On Home Screen)

### ISSUE THREAD

**Issue by raj-rathod** [Sorabhkumar-dev/food-odering-app#2]
When back click on home screen blank screen is coming

- please check this is issue
- it is coming in Samsung A50

**Comment by Sorabhkumar-dev** [comment]
Thanks Raj rathod for your contribution i working to resolve this issue.

**Comment by Sorabhkumar-dev** [comment]
thanks raj rathod i fixed this issue

**Comment by raj-rathod** [comment]
good work @Sorabhkumar-dev
